In [342]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [343]:
moseq = pd.read_csv('/Users/novak/Documents/Columbia/mentored_research/Turi/kpms_data_for_daart/ptsd9_recall4_28-4DLC_resnet50_phi_cfc_boxNov7shuffle1_388000.csv')
moseq.head()

,syllable,centroid x,centroid y,heading,latent_state 0,latent_state 1,latent_state 2,latent_state 3,latent_state 4
0,3,74.3618,49.0325,-1.1699,-2.5467,-3.8798,1.3044,-4.0989,-1.8243
1,3,74.4101,49.3188,-2.2658,4.8712,-1.3823,-4.5508,3.0541,-2.3487
2,3,74.2889,48.6499,0.0278,1.1314,-0.6536,1.8400,0.2583,1.1340
3,3,74.9410,48.9259,-0.0397,1.3232,-0.5899,2.1412,0.1143,1.2999
4,3,74.3464,49.2924,-0.1920,1.1570,-0.5138,1.6575,-0.1825,1.4145

In [344]:
encoder = OneHotEncoder()
encoded_data = encoder.fit_transform(moseq[['syllable']])
encoded_df = pd.DataFrame(encoded_data.toarray(), columns=encoder.get_feature_names_out(['syllable']))

In [345]:
background_name_num = [8, 10, 11, 15, 16, 17, 18, 19, 20, 21, 23, 24, 25, 26, 27, 28, 29, 31, 32, 36, 37, 38, 39, 40, 46, 49, 52, 53, 54, 57, 58, 59, 60, 62, 71, 73, 76, 86, 91, 92]
drop_name = []
for i in background_name_num:
    drop_name.append('syllable_' + str(i))
drop_index = encoded_df.columns.get_indexer(drop_name)
drop_index = [x for x in drop_index if x != -1]
drop_df = encoded_df.iloc[:, drop_index]

In [346]:
background_df = drop_df.max(axis=1)
keep_df = encoded_df.drop(columns=encoded_df.columns[drop_index], axis=1)
final_df = pd.concat([keep_df, background_df], axis=1)

final_df = final_df.rename(columns={0: 'background'})

final_df = final_df[sorted(final_df.columns)]

final_df

,background,syllable_0,syllable_1,syllable_12,syllable_13,syllable_14,syllable_2,syllable_3,syllable_4,syllable_5,syllable_6,syllable_7,syllable_9
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1119,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1120,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1121,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1122,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1123,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [347]:
final_df.to_csv('/Users/novak/Documents/Columbia/mentored_research/Turi/daart/labels-hand/ptsd9_28_4_recall4.csv')